---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "whiteboard-app-service"
  namespace: "default"
  labels:
    app: "whiteboard-app"
spec:
  ports:
  - name: "80-to-3000-tcp"
    protocol: "TCP"
    port: 80
    targetPort: 80
  - name: "8080-to-8080-tcp"
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "whiteboard-app"
  type: "LoadBalancer"
  loadBalancerIP: ""
